name: wallpaper_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.1.1
  day_night_switcher: ^0.2.0+1
  flutter_slidable: ^2.0.0
  reorderableitemsview: ^2.0.1
  bootstrap_flutter: ^1.0.0
  flutter_hsvcolor_picker: ^1.2.3
  flame: 1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  carousel_slider: ^4.2.1

flutter:
  assets:
    - assets/images/Okayu_Movement.png

  uses-material-design: true